pipeline{
agent any
stages
{
stage('Build')
{
steps{
echo "Building the Code.........."
bat "mvn -f hospital-service/pom.xml clean"
}
}
stage('Test')
{
steps{
echo "Testing the Code.........."
bat "mvn -f hospital-service/pom.xml test"
}
}
stage('Compile')
{
steps{
echo "Compiling the Project.........."
bat "mvn -f hospital-service/pom.xml compile"
}
}
stage('Deploy')
{
steps{
echo "Deploying the Project.........."
}
}
}
}
