FROM openjdk:12.0.1-jdk
MAINTAINER Palvan Rozyyev <pelvan657@yahoo.com>
COPY /target/configurationService.jar configurationService.jar
ENTRYPOINT ["java", "-jar", "configurationService.jar"]
EXPOSE 8888