FROM openjdk:12.0.1-jdk
MAINTAINER Palvan Rozyyev <pelvan657@yahoo.com>
COPY /target/hystrixdashboardService.jar hystrixdashboardService.jar
ENTRYPOINT ["java", "-jar", "hystrixdashboardService.jar"]
EXPOSE 8070